project:
  type: website
  output-dir: docs

website:
  title: "williamyip1112"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    scss: mystyles.scss
    toc: true

editor: visual

