project:
  type: website
  output-dir: docs

website:
  title: "William Yip"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Skillsets.qmd
      - Experiences.qmd

format:
  html:
    theme: 
      - journal
      - mystyles.scss
    toc: true

editor: visual

