---
title: "Experiences"
---

-   **Eagle Project: Arroyo Seco Mulching, South Pasadena** September 2018

    -   Led a team of 10 recruited volunteers in mulching a large patch of arid land in the Arroyo Seco Park of South Pasadena 

    -   Added aesthetic value to the land and paved way for new possibilities of land use for the city

    -   Scheduled meetings with public works managers and district leaders for Boy Scouts to obtain approval for the project and discussed logistics

    -   Documented project costs and created a work schedule to meet project deadlines

-   **Elite Performance and Rehabilitation Center, Internship**		March 2022 - May 2022

    -   Gained experience working with patients and athletes with a variety of conditions

    -   Performed exercises with patients and assisted aids in walking through exercises with patients

-   **Professional Physical Therapy, Shadow Experience** August 2022 - August 2022

    -   Observed Physical Therapists working with patients

    -   Developed knowledge of diagnosis and treatment process 

    -   Assisted in walking through exercises with patients

-   Your Children\'s Trees, Treasurer and Grant Coordinator			March 2022 - Present 

    -   Lead volunteers in tree-planting projects

    -   Educate children on the importance of trees

    -   Monitor financial activity of the organization and apply for grants
